# pg version 3.x
#   gem install pg
#
#   Ensure the pg 3 gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_PG_PORT") { 5432 } %>

development:
  <<: *default
  database: recipes_development

test:
  <<: *default
  database: recipes_test

production:
  <<: *default
  database: recipes_production
  url: <%= ENV['DATABASE_URL'] %>
